PROJECT_ROOT_DIR: /data/xuth/deep_ipr/new2024


gpu: 5
lr: 0.0005
epochs: 100
batch_size: 128
weight_decay: 0.0005
seed: 42
model_type: source

dataset_name: cifar10
classes: 10
mean: [0.4914, 0.4822, 0.4465]
std: [0.2023, 0.1994, 0.2010]
